services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: fastapi run main.py --host 0.0.0.0 --port 8000